Fix None check in update_chart to work with DataFrames
What we have now will fail if you submit a DataFrame, saying:


ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().